/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Block(props) {
  const { nodes, materials } = useGLTF("/blockEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_22.geometry}
        material={materials.material}
        position={[174.5, 0, -168.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_22001.geometry}
        material={materials.material}
        position={[174.5, 0, -168.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_22002.geometry}
        material={materials.material}
        position={[174.5, 0, -168.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_22003.geometry}
        material={materials.material}
        position={[174.5, 0, -168.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_23.geometry}
        material={materials.material}
        position={[175.25, 0, -168]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_23001.geometry}
        material={materials.material}
        position={[175.25, 0, -168]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_23002.geometry}
        material={materials.material}
        position={[175.25, 0, -168]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_24.geometry}
        material={materials.material}
        position={[168.75, 16, -168]}
        rotation={[-Math.PI, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_24001.geometry}
        material={materials.material}
        position={[168.75, 16, -168]}
        rotation={[-Math.PI, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_24002.geometry}
        material={materials.material}
        position={[168.75, 16, -168]}
        rotation={[-Math.PI, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_25.geometry}
        material={materials.material}
        position={[169.5, 16, -168.5]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_25001.geometry}
        material={materials.material}
        position={[169.5, 16, -168.5]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_25002.geometry}
        material={materials.material}
        position={[169.5, 16, -168.5]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_25003.geometry}
        material={materials.material}
        position={[169.5, 16, -168.5]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_26.geometry}
        material={materials.material}
        position={[168.75, 8.75, -168]}
        rotation={[-Math.PI, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_26001.geometry}
        material={materials.material}
        position={[168.75, 8.75, -168]}
        rotation={[-Math.PI, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_26002.geometry}
        material={materials.material}
        position={[168.75, 8.75, -168]}
        rotation={[-Math.PI, -1.571, 0]}
      />
    </group>
  );
}

useGLTF.preload("/blockEliGfell.glb");
