/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Floor(props) {
  const { nodes, materials } = useGLTF("/floorEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes.SketchUp001.geometry}
        material={materials["_0128_White.001"]}
        scale={1}
        // scale={0.025}
      />
    </group>
  );
}

useGLTF.preload("/floorEliGfell.glb");
