/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Horse(props) {
  const { nodes, materials } = useGLTF("/horseEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_32.geometry}
        material={materials.Color_M00}
        position={[162.211, 30.5, -55.161]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_33.geometry}
        material={materials.Color_M00}
        position={[165.393, 0, -56.929]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_34.geometry}
        material={materials.Color_M00}
        position={[163.979, 0, -53.393]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_35.geometry}
        material={materials.Color_M00}
        position={[162.919, 27.5, -54.454]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_36.geometry}
        material={materials.Color_M00}
        position={[184.132, 0, -73.546]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_37.geometry}
        material={materials.Color_M00}
        position={[185.546, 0, -77.081]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/horseEliGfell.glb");
