/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Room(props) {
  const { nodes, materials } = useGLTF("/roomEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SketchUp.geometry}
        material={materials._0128_White}
        scale={1}
        // scale={0.025}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_15002.geometry}
          material={materials.material}
          position={[63.875, 14.242, -160.086]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42001.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42002.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42003.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42004.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42005.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42006.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42007.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42008.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42009.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42010.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42011.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42012.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42013.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42014.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42015.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43001.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43002.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43003.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43004.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43005.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43006.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43007.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43008.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43009.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43010.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43011.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43012.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43013.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43014.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43015.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43016.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43017.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_44.geometry}
          material={materials._0128_White}
          position={[240, 0, -70.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_45.geometry}
          material={materials._0128_White}
          position={[239, 0, -67.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_46.geometry}
          material={materials._0128_White}
          position={[66, 30.5, -238]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SketchUp001.geometry}
        material={materials._0128_White}
        scale={1}
        // scale={0.025}
      />
    </group>
  );
}

useGLTF.preload("/roomEliGfell.glb");
