/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ShelfBShort(props) {
  const { nodes, materials } = useGLTF("/shelfBShortEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_38.geometry}
        material={materials.material}
        position={[144, 44, -6]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_39.geometry}
        material={materials.material}
        position={[146, 45.5, -0.75]}
        rotation={[0, -1.571, 0]}
      />
    </group>
  );
}

useGLTF.preload("/shelfBShortEliGfell.glb");
