/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ShelfAShort(props) {
  const { nodes, materials } = useGLTF("/shelfAShort.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_40.geometry}
        material={materials.material}
        position={[193, 57.5, -0.75]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_41.geometry}
        material={materials.material}
        position={[192, 56, -4]}
        rotation={[0, -1.571, 0]}
      />
    </group>
  );
}

useGLTF.preload("/shelfAShort.glb");
