/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ShelfBLong(props) {
  const { nodes, materials } = useGLTF("/shelfBLongEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_48.geometry}
        material={materials.material}
        position={[6, 56, -208]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_50.geometry}
        material={materials.material}
        position={[0.75, 57.5, -206]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/shelfBLongEliGfell.glb");
