/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ShelfALong(props) {
  const { nodes, materials } = useGLTF("/shelfALong.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_47.geometry}
        material={materials.material}
        position={[4, 44, -144]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_49.geometry}
        material={materials.material}
        position={[0.75, 45.5, -144]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/shelfALong.glb");
