/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/eliModels.glb");
  return (
    <group {...props} dispose={null} position={[-60, 1, 60]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SketchUp.geometry}
        material={materials._0128_White}
        scale={0.5} // scale={0.0254}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_0.geometry}
          material={materials.material}
          position={[70.9853, 0, -76.2157]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_1.geometry}
          material={materials.material}
          position={[70.9853, 14.5, -66.2157]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_14.geometry}
          material={materials.material}
          position={[63.875, -0.2582, -174.5861]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_15.geometry}
          material={materials.material}
          position={[63.875, 14.2418, -160.0861]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_15003.geometry}
          material={materials.material}
          position={[63.875, 14.2418, -160.0861]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_15004.geometry}
          material={materials.material}
          position={[63.875, 14.2418, -160.0861]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_16.geometry}
          material={materials.material}
          position={[69.125, 10.2418, -160.8361]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_17.geometry}
          material={materials.material}
          position={[75.875, -0.2582, -161.5861]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_2.geometry}
          material={materials.material}
          position={[66.2353, 16.5, -70.9657]}
          rotation={[Math.PI, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_22.geometry}
          material={materials.material}
          position={[174.5, 0, -168.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_22001.geometry}
          material={materials.material}
          position={[174.5, 0, -168.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_22002.geometry}
          material={materials.material}
          position={[174.5, 0, -168.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_22003.geometry}
          material={materials.material}
          position={[174.5, 0, -168.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_23.geometry}
          material={materials.material}
          position={[175.25, 0, -168]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_23001.geometry}
          material={materials.material}
          position={[175.25, 0, -168]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_23002.geometry}
          material={materials.material}
          position={[175.25, 0, -168]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_24.geometry}
          material={materials.material}
          position={[168.75, 16, -168]}
          rotation={[-Math.PI, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_24001.geometry}
          material={materials.material}
          position={[168.75, 16, -168]}
          rotation={[-Math.PI, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_24002.geometry}
          material={materials.material}
          position={[168.75, 16, -168]}
          rotation={[-Math.PI, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_25.geometry}
          material={materials.material}
          position={[169.5, 16, -168.5]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_25001.geometry}
          material={materials.material}
          position={[169.5, 16, -168.5]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_25002.geometry}
          material={materials.material}
          position={[169.5, 16, -168.5]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_25003.geometry}
          material={materials.material}
          position={[169.5, 16, -168.5]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_26.geometry}
          material={materials.material}
          position={[168.75, 8.75, -168]}
          rotation={[-Math.PI, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_26001.geometry}
          material={materials.material}
          position={[168.75, 8.75, -168]}
          rotation={[-Math.PI, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_26002.geometry}
          material={materials.material}
          position={[168.75, 8.75, -168]}
          rotation={[-Math.PI, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_3.geometry}
          material={materials.material}
          position={[64, 16.5, -64]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_3001.geometry}
          material={materials.material}
          position={[64, 16.5, -64]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_3002.geometry}
          material={materials.material}
          position={[64, 16.5, -64]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_3003.geometry}
          material={materials.material}
          position={[64, 16.5, -64]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_3004.geometry}
          material={materials.material}
          position={[64, 16.5, -64]}
        />
        <group position={[64, 16.5, -64]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ID54.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ID54_1.geometry}
            material={materials._0128_White}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_32.geometry}
          material={materials.Color_M00}
          position={[162.2114, 30.5, -55.1612]}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_33.geometry}
          material={materials.Color_M00}
          position={[165.3934, 0, -56.9289]}
          rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_34.geometry}
          material={materials.Color_M00}
          position={[163.9792, 0, -53.3934]}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_35.geometry}
          material={materials.Color_M00}
          position={[162.9185, 27.5, -54.4541]}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_36.geometry}
          material={materials.Color_M00}
          position={[184.1317, 0, -73.5459]}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_37.geometry}
          material={materials.Color_M00}
          position={[185.5459, 0, -77.0815]}
          rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_38.geometry}
          material={materials.material}
          position={[144, 44, -6]}
          rotation={[0, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_38001.geometry}
          material={materials.material}
          position={[144, 44, -6]}
          rotation={[0, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_39.geometry}
          material={materials.material}
          position={[146, 45.5, -0.75]}
          rotation={[0, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_4.geometry}
          material={materials.material}
          position={[72.4853, 0, -67.2157]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_40.geometry}
          material={materials.material}
          position={[193, 57.5, -0.75]}
          rotation={[0, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_41.geometry}
          material={materials.material}
          position={[192, 56, -4]}
          rotation={[0, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42001.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42002.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42003.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42004.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42005.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42006.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42007.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42008.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42009.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42010.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42011.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42012.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42013.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42014.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_42015.geometry}
          material={materials._0128_White}
          position={[-3.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43001.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43002.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43003.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43004.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43005.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43006.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43007.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43008.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43009.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43010.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43011.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43012.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43013.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43014.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43015.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43016.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_43017.geometry}
          material={materials._0128_White}
          position={[240, 0, 3.5]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_44.geometry}
          material={materials._0128_White}
          position={[240, 0, -70.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_45.geometry}
          material={materials._0128_White}
          position={[239, 0, -67.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_46.geometry}
          material={materials._0128_White}
          position={[66, 30.5, -238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_47.geometry}
          material={materials.material}
          position={[4, 44, -144]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_48.geometry}
          material={materials.material}
          position={[6, 56, -208]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_48001.geometry}
          material={materials.material}
          position={[6, 56, -208]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_49.geometry}
          material={materials.material}
          position={[0.75, 45.5, -144]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_5.geometry}
          material={materials.material}
          position={[76.2353, 0, -72.4657]}
          rotation={[0, -1.5705, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_50.geometry}
          material={materials.material}
          position={[0.75, 57.5, -206]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.instance_6.geometry}
          material={materials.material}
          position={[67.2353, 0, -70.9657]}
          rotation={[0, 1.5705, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SketchUp001.geometry}
        material={materials._0128_White}
        scale={0.0254}
      />
    </group>
  );
}

useGLTF.preload("/eliModels.glb");
