/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Squatter(props) {
  const { nodes, materials } = useGLTF("/squatterEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_14.geometry}
        material={materials.material}
        position={[63.875, -0.258, -174.586]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_15.geometry}
        material={materials.material}
        position={[63.875, 14.242, -160.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_15001.geometry}
        material={materials.material}
        position={[63.875, 14.242, -160.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_15002.geometry}
        material={materials.material}
        position={[63.875, 14.242, -160.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_15003.geometry}
        material={materials.material}
        position={[63.875, 14.242, -160.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_15004.geometry}
        material={materials.material}
        position={[63.875, 14.242, -160.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_16.geometry}
        material={materials.material}
        position={[69.125, 10.242, -160.836]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_17.geometry}
        material={materials.material}
        position={[75.875, -0.258, -161.586]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/squatterEliGfell.glb");
