/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Stool(props) {
  const { nodes, materials } = useGLTF("/stoolEliGfell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_0.geometry}
        material={materials.material}
        position={[70.985, 0, -76.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_1.geometry}
        material={materials.material}
        position={[70.985, 14.5, -66.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_2.geometry}
        material={materials.material}
        position={[66.235, 16.5, -70.966]}
        rotation={[Math.PI, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_3.geometry}
        material={materials.material}
        position={[64, 16.5, -64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_3001.geometry}
        material={materials.material}
        position={[64, 16.5, -64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_3002.geometry}
        material={materials.material}
        position={[64, 16.5, -64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_3003.geometry}
        material={materials.material}
        position={[64, 16.5, -64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_3004.geometry}
        material={materials.material}
        position={[64, 16.5, -64]}
      />
      <group position={[64, 16.5, -64]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ID54.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ID54_1.geometry}
          material={materials._0128_White}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_4.geometry}
        material={materials.material}
        position={[72.485, 0, -67.216]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_5.geometry}
        material={materials.material}
        position={[76.235, 0, -72.466]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instance_6.geometry}
        material={materials.material}
        position={[67.235, 0, -70.966]}
        rotation={[0, 1.571, 0]}
      />
    </group>
  );
}

useGLTF.preload("/stoolEliGfell.glb");
